apiVersion: apps/v1
kind: Deployment
metadata:
  name: custombucks-backend
  namespace: custombucks
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custombucks-backend
  template:
    metadata:
      labels:
        app: custombucks-backend
    spec:
      containers:
      - name: custombucks-backend
        image: cheesecrust/custombucks-backend:latest
        ports:
        - containerPort: 8080

        env:
        # Database Configuration
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service.mysql-service.svc.cluster.local:3306/custombucks?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password

        # Application Configuration
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

        # Google Cloud Credentials
        - name: SPRING_AI_VERTEX_AI_CREDENTIALS_JSON
          value: "file:/app/credentials/gen-lang-client-0016462667-8bc77c22b03e.json"

        # Volume Mounts - 디렉토리로 마운트 (중복 제거!)
        volumeMounts:
        - name: google-credentials
          mountPath: /app/credentials
          readOnly: true

        # Resources
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        # Health Checks
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

      # Volumes
      volumes:
      - name: google-credentials
        secret:
          secretName: mysql-secret
          items:
          - key: gen-lang-client-0016462667-8bc77c22b03e.json
            path: gen-lang-client-0016462667-8bc77c22b03e.json
            