apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-service
  labels:
    app: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        
        env:
        # Root 비밀번호
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: db-password
        
        # 데이터베이스 자동 생성 (첫 번째 DB만 자동 생성됨)
        - name: MYSQL_DATABASE
          value: "authdb"

        # 추가 데이터베이스는 initdb 스크립트나 수동으로 생성 필요
        # custombucks 데이터베이스는 별도로 생성
        
        # 문자셋
        - name: MYSQL_CHARACTER_SET_SERVER
          value: "utf8mb4"
        - name: MYSQL_COLLATION_SERVER
          value: "utf8mb4_unicode_ci"
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # Health Check
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysql -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        
        # 데이터 저장 (⚠️ Pod 삭제 시 데이터 삭제됨!)
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: mysql-data
        emptyDir: {}